msse-chem-280-2024/periodic-table

elements/sodium.md

This PR adds a page for sodium

add sodium page

---

elements/oxygen.md

Added oxygen page

---

elements/fluorine.md

Add fluorine page

---

elements/helium.md

Added Fun Fact about Helium

---

elements/nitrogen.md

This PR adds a page for nitrogen.

add nitrogen page

---

elements/hydrogen.md

Adding hydrogen page through markdown file "hydrogen.md". Page contains element name, symbol, and 3 fun facts about hydrogen. 

add hydrogen page

---

elements/bismuth.md

Add bismuth page to periodic table with information about atomic symbol and number as well as facts about radioactivity.

Add bismuth page

---

elements/calcium.md

Add Calcium page

---

elements/boron.md

Adding a page on boron to the MSSE periodic table website. 

add boron page

---

elements/carbon.md

add Carbon page

---

elements/rhodium.md

This is to check the code input for the element Rhodium.

add Rhodium page

---

elements/tungsten.md

Adding tungsten page with element symbol, atomic number, and fun facts.

add tungsten page

---

elements/boron.md

Reverts msse-chem-280-2024/periodic-table#70

Revert "add boron page"

---

elements/Einsteinium.md

Added Einsteinium symbol, atomic number, and facts about the element 

add Einsteinium page

---

elements/tungsten.md

Fixed atomic number on tungsten page

fixed atomic number on tungsten page

---

elements/Lead.md

I have provided information about the Lead which is the 82nd element on the Periodic table.

Add Lead page

---

elements/Palladium.md

Added Palladium information. Waiting for reviewer to approve

update Palladium page

---

elements/molybdenum.md

update molybdenum page

---

Xenon.md

add Xenon to the elements page

---

elements/Berkelium.md

Made a Berkelium.md file for periodic table project
1. Did they use the right page format?
2. Is their file name correct?
3. Did they add information about the element?

add Berkelium page

---

elements/iodine.md

This pull request is to update the iodine page.

update iodine page

---

elements/magnesium.md

Add magnesium page

---

elements/mercury.md

Added Mercury Page

---

elements/osmium.md

This PR adds a page for Osmium

Add Osmium page

---

elements/Astatine.md

I added the  Astatine page 

---

elements/gallium.md

Added information about gallium, the element symbol, atomic number, and three facts. 

Add gallium page

---

elements/Actinium.md

Added Actinium file

---

elements/polonium.md

Adds information about polonium.

update polonium page

---

elements/erbium.md

add erbium page

---

elements/phosphorus.md

Add phosphorus page to the periodic table

Add Phosphorus Page

---

elements/americium.md

Created a pull request for MSSE assignment.

update americium page

---

elements/calcium.md

Updated the Calcium page to include spaces.

updated Calcium page to include spaces

---

elements/Radon.md

PR to add Radon page with facts to website

add RADON page

---

elements/iron.md/Iron 

I updated the missing iron page 

add iron page 

---

elements/gold.md

Adds the Gold element page
Closes #58

Added Gold

---

elements/californium.md

This PR adds a page for the element Californium
none
closes #31

Add Californium page

---

elements/nitrogen.md

Updated fun facts section for nitrogen page

update nitrogen page

---

elements/krypton.md

Created krypton page and added information about the element.
- Created a markdown file for krypton

add krypton page

---

elements/lawrencium.md

update Lawrencium page

---

elements/Thorium.md

Review the quality of this thorium page

Creating and filling out Thorium info for the web page.

---

elements/astatine.md

Update and rename Astatine.md to astatine.md

---

elements/cesium.md

PR to add Cesium element page.

add cesium page

---

elements/arsenic.md

add arsenic page

---

elements/uranium.md

I add an information of uranium

Add Uranium page

---

elements/yttrium.md

added a space for the lines

---

elements/silicon.md

Added page for element Silicon & included atomic number & fun facts

Update Silicon page

---

elements/calcium.md

Update Calcium page with more facts

updated Calcium page with more facts

---

elements/boron.md

Added more facts to boron page. 

added more facts to boron page

---

elements/Lead.md

Added new lines in the fun facts.

added new lines

---

elements/gold.md

Reformatted so symbol and atomic number is multiline

Gold - reformat doc

---

elements/radon.md

PR to change file name from Radon.py to radon.py -- needs to be lowercase

Change file name

---

elements/francium.md

Francium page created, added information about francium and now issuing a pull requerst for class

Add francium page

---

elements/Livermorium.md

Completed the push of livermorium, request peer review

Update to Livermorium page

---

elements/Copper.md

added details of element and fun facts

updated page with Copper facts

---

elements/hydrogen.md 

Revision hydrogen page with correct formatting, title, and facts. 

Revising Hydrogen page

---

elements/chlorine.md

I updated the chlorine page to include two more interesting facts.

Updated Chlorine Page 

---

elements/magnesium.md

updated Magnesium page to include spaces

---

elements/helium.md

More information was added about Helium

Added more information about helium

---

elements/barium.md

I have added the barium element on the periodic table, and added three fun facts about Barium.

Add Barium page

---

elements/manganese.md

PR adds information about manganese to the repo
- [ x] added page containing information about manganese
- does this look good ?
- [ x] Ready to go

add manganese page

---

elements/Tellurium.md

Add Tellurium Page

---

elements/iron.md

The iron page is updated to have more facts about the element 

Updated iron page 

---

elements/silver.md

Added information for silver page
- Creates a silver page

add silver page

---

elements/silicon.md

Feedback response, Changed sentence structure & added hyperlinks to key terms

---

elements/radium.md

added atomic symbol, atomic number and a brief description of the element radium

updating radium page

---

elements/hydrogen.md

Revising hydrogen page so that it turns blue on the periodic table. (Contains title, element name/#, and facts).

revise hydrogen page (revision 6, turn blue on table)
